version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./frontend/wordpress-ecommerce:/var/www/html/wp-content/themes/custom
    depends_on:
      - db

  laravel:
    image: php:8.2-apache
    ports:
      - "8000:80"
    volumes:
      - ./backend/ecommerce-backend-wordpress:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: >
      bash -c "
      apt-get update && 
      apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip git &&
      docker-php-ext-install pdo_mysql gd &&
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
      cd /var/www/html &&
      composer install --no-dev &&
      cp .env.example .env || true &&
      php artisan key:generate --force &&
      sed -i 's/^APACHE_DOCUMENT_ROOT=.*/APACHE_DOCUMENT_ROOT=\/var\/www\/html\/public/' /etc/apache2/envvars &&
      echo 'DocumentRoot /var/www/html/public' > /etc/apache2/sites-available/000-default.conf &&
      echo '<Directory /var/www/html/public>' >> /etc/apache2/sites-available/000-default.conf &&
      echo '    AllowOverride All' >> /etc/apache2/sites-available/000-default.conf &&
      echo '</Directory>' >> /etc/apache2/sites-available/000-default.conf &&
      a2enmod rewrite &&
      apache2-foreground
      "
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password

volumes:
  db_data:
  wordpress_data: